
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">

            <div class="panel-body" style="margin-top: 10%; border: 1px solid #a8a8a8">
                <form role="form" action="login.php" method="POST">

                    <div class="form-group input-group">
                        <span class="input-group-addon"><i class="fa fa-tag"></i> </span>
                        <input type="text" name="nama" placeholder="Nama Lengkap" class="form-control" required></br>
                    </div>

                    <div class="form-group input-group">
                        <span class="input-group-addon"></span>
                        <input type="text" name="alamat" placeholder="Alamat" class="form-control" required></br>
                    </div>

                    <div class="form-group input-group">
                        <span class="input-group-addon"></span>
                        <input type="text" name="kota" placeholder="Kota" class="form-control" required></br>
                    </div>

                    <div class="form-group input-group">
                        <span class="input-group-addon"></span>
                        <input type="text" name="provinsi" placeholder="Provinsi" class="form-control" required></br>
                    </div>

                    <div class="form-group input-group">
                        <span class="input-group-addon"></span>
                        <input type="text" name="Email" placeholder="Email" class="form-control" required></br>
                    </div>

                    <!--div class="form-group input-group">
                        <span class="input-group"></span>
                        <input type="checkbox" name="remember" placeholder="remember" > Remember Me</br>
                    </div-->

                    <!--div class="form-group">
                            <span class="pull-right">
                                <a style="font-size: 11px" href="lupa.html">Lupa Password?</a>
                            </span>
                    </div-->
                    <button class="btn btn-primary" type="submit" name="login">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>
