<div class="container">
    <div class="row">
        <form role="form" action="import.php" method="POST">

            <div class="form-group input-group">
                <span class="input-group-addon"></span>
                <input type="text" name="pilihanaction" placeholder="Action" class="form-control" required></br>
            </div>

            <div class="form-group input-group">
                <span class="input-group-addon"></span>
                <input type="text" name="separator" placeholder="Separator" class="form-control" required></br>
            </div>
            <div class="form-group">
                <span class="input-group"></span>
            </div>
            <div class="form-group">
                <span class="input-group"></span>
            </div>
            <div class="form-group">
                <span class="pull-right">
                    <button onclick="" class="btn btn-primary" type="submit" name="login" >File Chooser</button>
                </span>
            </div>
        </form>
    </div>
</div>
